SET search_path = PUBLIC, pg_catalog;
SET default_tablespace = '';
SET default_with_oids = FALSE;

CREATE TABLE IF NOT EXISTS TBL_ACCOUNT
(
  ID                UUID NOT NULL,
  TYPE              CHARACTER VARYING(20),
  USERNAME          CHARACTER VARYING(30),
  FIRST_NAME          CHARACTER VARYING(30),
  LAST_NAME          CHARACTER VARYING(30),
  USER_INTERFACE_ID CHARACTER VARYING(50),
  LANG              CHARACTER VARYING (10),
  CONSTRAINT primary_key_tbl_account PRIMARY KEY (ID),
  CONSTRAINT unique_tbl_account UNIQUE (TYPE, USERNAME)
);
CREATE TABLE IF NOT EXISTS TBL_AUDIT
(
  ID       UUID NOT NULL,
  ACTOR_ID UUID NOT NULL,
  DATE     TIMESTAMP WITHOUT TIME ZONE,
  ROOM_ID   CHARACTER VARYING(30),
  ACTION   CHARACTER VARYING(20),
  CONSTRAINT primary_key_tbl_audit PRIMARY KEY (ID),
  CONSTRAINT rel_tbl_audit_account FOREIGN KEY (ACTOR_ID) REFERENCES TBL_ACCOUNT (ID) ON DELETE CASCADE
);
